remote_theme: pages-themes/cayman@v0.2.0
title: Afghansk Catering
description: Afghansk Catering tilbyr mat fra Afghanistan til alle anledninger i Stavanger
github:
  is_project_page: false
  show_downloads: false
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
